### ISSUE TITLE
v0.4.1 KeyError: 8 line 502 and ModuleError: name '_print' is not defined

### ISSUE THREAD

**Issue by ozzieem** [theace0296/BeatMapSynthesizer#3]
Hi, just wanted to let you know that I'm getting a KeyError on line 502 and a ModuleError when trying to generate a map with v0.4.1. I can generate a map properly with v0.4.0 so I assume an older version of beatmapsynth.py is used in that version.

When I check latest beatmapsynth.py it seems like that row  (502) is outcommented but I haven't checked further on why that might be. Maybe it's best to update to that version for v0.4.1 or if it's going to be a new version, I guess it's up to you.

Here's a screenshot of the console printout if it helps:

![image](https://user-images.githubusercontent.com/14169503/87834995-2cc05400-c88c-11ea-91f8-b70e26c32689.png)

**Comment by theace0296** [comment]
I haven't been active in awhile, but I've been having issues with pyinstaller lately. They haven't released the dev branch yet and it's the only version that works with 3.8.5. I might release a 0.5-dev that would require Python to be installed.

**Comment by theace0296** [comment]
Try the pre-release and see if the issue has gone away: https://github.com/theace0296/BeatMapSynthesizer/releases/tag/v0.5.0-dev

**Comment by ozzieem** [comment]
Hi, thanks for the reply. I tried with v0.5.0-dev as suggested and I'm getting the error that I reported before however it got stuck on an error where it couldn't find the numba.decorators method. I figured it was because of version v0.50 that apparently was installed where that method has been removed but I reinstalled version 0.48 and it managed to go further, generating the folders for the song but with no content this time. According to the traceback it seems to encounter a MemoryError when trying to load the model (?):

```
initFiles - Installed Python packages.
initFiles - Files Updated.
initFiles - Updating script file.
initFiles - Script file updated.
initFiles - Checking for version info.
initFiles - Updating version info.
initFiles - Updating model files.
Python 3.8.1
initFiles - Installing Python packages.
initFiles - Installed Python packages.
initFiles - Files Updated.
generateBeatMaps - Start
generateBeatMaps - Start
generateBeatMaps - Metadata Loaded
generateBeatMaps - Song Title Found
generateBeatMaps - Artist Found
generateBeatMaps - Checking if beat map exists
generateBeatMaps - Searching for embedded art
generateBeatMaps - Embedded art found!
generateBeatMaps - Search for embedded art finished
generateBeatMaps - Embedded art processing!
generateBeatMaps - Embedded art writing!
generateBeatMaps - Setting beat map parameters
generateBeatMaps - Generating beat map
Traceback (most recent call last):
  File "../AppData/Roaming/beat-map-synthesizer/temp/beatmapsynth.py", line 1310, in <module>
    main.run_model(main.difficulty.casefold()))
  File "../AppData/Roaming/beat-map-synthesizer/temp/beatmapsynth.py", line 521, in run_model
    return self.rate_modulated_segmented_hmm_notes_writer(difficulty)
  File "../AppData/Roaming/beat-map-synthesizer/temp/beatmapsynth.py", line 1213, in rate_modulated_segmented_hmm_notes_writer
    MC = self.load_hmm_model(difficulty)
  File "../AppData/Roaming/beat-map-synthesizer/temp/beatmapsynth.py", line 839, in load_hmm_model
    MC = pickle.load(m)
MemoryError
generateBeatMaps - Finished
```

I also tried removing associated AppData files and tried all different models if that might be it but to no avail. Not sure what to make of the MemoryError, but if this version works fine for you then I guess it's something locally for me but not sure where to look.

**Comment by theace0296** [comment]
From the log I see you have Python installed, is it the 32 bit or 64 bit version? The MemoryError usually only comes up when using a 32 bit version of Python.
